# Clears the environment
rm(list = ls())

source("90_LIBS_CONSTANTS.R")
source("01.1_FAO_DATA_READING.R")
source("01.2_FAO_DATA_CONSOLIDATION.R")
source("01.3_FAO_DATA_DESCRIPTION.R")
source("02_IOTC_DATA.R")
source("03_COMP_CATCH_FLEET.R")
source("04_COMP_CATCH_SPECIES.R")
source("05_COMP_CATCH_YEAR.R")
source("06_COMP_CATCH_YEAR_SPECIES.R")
source("07_COMP_CATCH_YEAR_FLEET.R")
source("08_COMP_YEAR_FLEET_AREA_SPECIES.R")